### ISSUE TITLE
Some feedback about the template

### ISSUE THREAD

**Issue by alinnert** [snyk-snippets/modern-npm-package#4]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Description

I found this repository today and find it pretty interesting since I also made something like this a few days ago and I want to share my thoughts and ideas about it:

- Can you make this repository a template? That way it's easier to start a new library from within GitHub.
- For a template it would be handy if it was as minimal as possible so you don't have to delete so many things after using it to start a new library. By that I mean for instance properties in the `package.json` like `description`, `repository`, `keywords`, `author`, etc.
- Do you really want to include test libraries? I think some people will just replace them with the alternative they prefer. Which means they have to do more work.
  - Also, the `README.md` mentions to install the testing libraries and to create the necessary files. But currently they're already there, so these step's are not necessary.

**Comment by clarkio** [comment]
Hey @alinnert thank you for opening this issue and sharing your feedback. It's great to hear you are working on something like this too. This could definitely be a candidate as a template however I wonder what implications it may have on the building and publishing workflows that are in place. I believe those rely on details like `author`, `repository`, etc. in order to work. Do you have suggestions around handling that which you've experienced in template repos?

**Comment by alinnert** [comment]
By building and publishing workflows do you mean those in the `.github` folder? I'd expect they are meant for the library repos that one would make using this template instead of the template itself. I don't know if they run in template repositories.

Honestly, I'm not sure what I was thinking by saying "remove those `package.json` properties". I think I've meant the values because the properties are necessary indeed.

In the end I think I've misinterpreted the purpose of this repo. I think it's meant to be more like a copy-and-paste template, right? I was in the mindset of "create a new library in some automated way using this template" like GitHub template repositories or `npm create vite` because I think something like this is really missing in the npm ecosystem.

In this context I have to admit the feedback is not that fitting - aside from point 3.1. Unless you're planning to make something like what I was thinking about originally. Sorry for the confusion 😅

**Comment by clarkio** [comment]
Yes, it's meant to be as a reference package that could be copied from instead of used as a template. I could definitely see something being created based on it, though to be used as a template instead. It sounds like we're in agreement on this so I will close the issue but feel free to let me know if you think differently and wish to continue discussion on it.
